"""Creating first tables

Revision ID: 05f2977884e4
Revises:
Create Date: 2024-02-24 13:01:36.113834

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05f2977884e4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), nullable=True, server_default=sa.func.now()
        ),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("short_description", sa.String(), nullable=True),
        sa.Column("long_bio", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name="username_unique"),
    )
    op.create_table(
        "liked_post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.TIMESTAMP(), nullable=True, server_default=sa.func.now()
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "post_id", name="user_post_unique"),
    )
    op.create_index("liked_post_user_id_idx", "liked_post", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("liked_post_user_id_idx", table_name="liked_post")
    op.drop_table("liked_post")
    op.drop_table("user")
    # ### end Alembic commands ###
