name: Tagged Release


on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    steps:
      - name: Tagged Release
        uses: "marvinpinto/action-automatic-release@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true